baseURL: 'https://boison.tw'
title: Boison
paginate: 10
defaultContentLanguage: zh-tw
theme: PaperMod

disqusShortname: boison-tw
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

permalinks:
  posts: '/:year/:month/:slug/'

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Boison
  description: 我關注生產力、網頁技術，行銷相關議題。目前在企業軟體公司擔任前端工程師
  keywords:
    - Blog
    - Portfolio
    - PaperMod
  author: Me
  images:
    - '<link or path of image for opengraph, twitter-cards>'
  DateFormat: 'January 2, 2006'
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false

  # Post
  hidemeta: false
  ShowBreadCrumbs: true
  ShowReadingTime: true
  comments: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  showtoc: true
  tocopen: false
  ShowShareButtons: true

  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    safari_pinned_tab:  "/safari-pinned-tab.svg"

    
  label:
    text: Boison
    iconHeight: 35

  profileMode:
    enabled: false
    title: ExampleSite
    subtitle: This is subtitle
    imageUrl: <img location>
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hi! I am Boison \U0001F44B"
    Content: 我關注生產力、網頁技術，行銷相關議題。目前在企業軟體公司擔任前端工程師。

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/Boison0720'
    - name: github
      url: 'https://github.com/BoisonChang'
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: archive
      name: Archive
      url:  archives/
      weight: 5
    - name: Search
      url:  search/
      weight: 7
    - identifier: tags
      name: Tag
      url:  tags/
      weight: 10

# Search Configs
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary